version: "3.9"

services:
  dusty:
    build: .
    container_name: dusty
    restart: unless-stopped

    environment:
      TOKEN: ${TOKEN}
      NODE_ENV: production

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs